development:
  adapter: postgresql
  database: silvergum_development
  pool: 5
  encoding: unicode
  min_messages: warning

test:
  adapter: postgresql
  database: silvergum_test
  pool: 5
  encoding: unicode
  min_messages: warning
